### ISSUE TITLE
Add function to check and read input types

### ISSUE THREAD

**Issue by gcperk** [ninoxconsulting/PEMprepr#31]
As suggested in review, we could add helper function to check and import spatRast and or vector inputs or filepaths. 

read_spatrast_if_necessary = function(spatRast){

if (inherits(spatRast, c("character"))) {
spatRast <- terra::rast(spatRast)

} else if (!inherits(spatRast, c("SpatRaster"))) {
cli::cli_abort("{.var spatRast} must be a SpatRaster or a path to a file")
}
return(spatRast)
}

`
Would need to update the functions where these are added in PEMprepr and PEMsamplr

**Comment by gcperk** [comment]
Added this with the following PR. A few checks - 1) does it need more documentation as an internal function? 2) Can i use this function in other PEMr packages (samplr?).

**Comment by ateucher** [comment]
Great idea to put it in PEMprepr! I don't think it needs more documentation, I do have an idea though to make the error messages more customized, so I will put in a PR. You can use it in PEMsamplr with `PEMprepr:::read_spatrast_if_necessary`. Normally accessing internal functions from another package isn't a good idea because it's liable to change without notification, but since it's your own package it's fine. I think `check()` will give a `NOTE`, but if you're okay with that I think it's fine.
